/***************************************************
Source for Chapter 5 , Example 5.4
How to use SAVEPOINT and ROLLBACK TO SAVEPOINT in any TRANSACTION
****************************************************/

DELIMITER $
DROP PROCEDURE IF EXISTS SAVEPOINT_ROLLBACK$
CREATE PROCEDURE SAVEPOINT_ROLLBACK(IN PARM_CATEGORY_ID INT,IN PARM_CATEGORY_NAME LONGTEXT,IN PARM_DESCRIPTION LONGTEXT,IN PARM_ITEM_ID INT,IN PARM_ITEM_NAME LONGTEXT,IN PARM_REF_CATEGORY_ID INT)
CATEGORIES_BLOCK : BEGIN
  DECLARE IS_CATEGORY_ID_EXISTS INT DEFAULT 0;
  DECLARE IS_CATEGORY_DUPLICATE INT DEFAULT 0;
  DECLARE TEMP_CATEGORY_ID INT;
  DECLARE CATEGORY_DUPLICATE_ERROR CONDITION FOR 1062;
  DECLARE CONTINUE HANDLER FOR CATEGORY_DUPLICATE_ERROR SET IS_CATEGORY_DUPLICATE = 1;
  SET TEMP_CATEGORY_ID = PARM_CATEGORY_ID;
  START TRANSACTION;
    SELECT COUNT(*) INTO IS_CATEGORY_ID_EXISTS FROM TBL_CATEGORIES WHERE CategoryID = PARM_CATEGORY_ID;
    IF IS_CATEGORY_ID_EXISTS THEN
      FIND_CATEGORY_ID_LOOP : LOOP
        SET IS_CATEGORY_DUPLICATE = 0;
        SET TEMP_CATEGORY_ID = TEMP_CATEGORY_ID + 1;
        INSERT INTO TBL_CATEGORIES(CategoryID,CategoryName,Description) VALUES (TEMP_CATEGORY_ID,PARM_CATEGORY_NAME,PARM_DESCRIPTION);
        IF NOT IS_CATEGORY_DUPLICATE THEN LEAVE FIND_CATEGORY_ID_LOOP; END IF;
      END LOOP FIND_CATEGORY_ID_LOOP;
    ELSE
      INSERT INTO TBL_CATEGORIES(CategoryID,CategoryName,Description) VALUES (PARM_CATEGORY_ID,PARM_CATEGORY_NAME,PARM_DESCRIPTION);
      SET IS_CATEGORY_ID_EXISTS = 0;
      SET IS_CATEGORY_DUPLICATE = 0;
    END IF;
  SAVEPOINT COMMIT_TBL_CATEGORIES;
    ITEMS_BLOCK : BEGIN
      DECLARE IS_ITEM_ID_EXISTS INT DEFAULT 0;
      DECLARE IS_REF_CATEGORY_ID_EXISTS INT DEFAULT 0;
      SELECT COUNT(*) INTO IS_REF_CATEGORY_ID_EXISTS FROM TBL_CATEGORIES WHERE CategoryID = PARM_REF_CATEGORY_ID;
      IF IS_REF_CATEGORY_ID_EXISTS THEN
        SELECT COUNT(*) INTO IS_ITEM_ID_EXISTS FROM TBL_ITEMS WHERE ItemID = PARM_ITEM_ID;
        IF IS_ITEM_ID_EXISTS THEN
          SELECT 'ROLLBACK TO SAVEPOINT IS ACTIVATED' AS 'RESULT';
          SELECT 'ItemID IS DUPLICATE ENTRY' AS 'WARNNING';
          ROLLBACK TO SAVEPOINT COMMIT_TBL_CATEGORIES;
        ELSE
          INSERT INTO TBL_ITEMS(ItemID,ItemName,CategoryID) VALUES (PARM_ITEM_ID,PARM_ITEM_NAME,PARM_REF_CATEGORY_ID);
          SELECT 'INSERT DATA TO TBL_CATEGORIES AND TBL_ITEMS COMPLETED' AS 'INFORMATION';
        END IF;
      ELSE
        SELECT 'ROLLBACK TO SAVEPOINT IS ACTIVATED' AS 'RESULT';
        SELECT 'NOT FOUND REFERENCE CategoryID FROM TBL_CATEGORIES' AS 'WARNNING';
        ROLLBACK TO SAVEPOINT COMMIT_TBL_CATEGORIES;
      END IF;
    END ITEMS_BLOCK;
  COMMIT;
END CATEGORIES_BLOCK$


/***************************************************
End of file
****************************************************/