/***************************************************
Source for Chapter 4 , Example (No run number)
PHP and MySQL
****************************************************/

DELIMITER $
DROP PROCEDURE IF EXISTS SET_DATA_CATEGORIES$
CREATE PROCEDURE SET_DATA_CATEGORIES(IN CATEGORY_ID INT,IN CATEGORY_NAME LONGTEXT,IN DESCRIPTION LONGTEXT)
BEGIN
  DECLARE DUPLICATE_ENTRY_ERROR CONDITION FOR 1062;
  DECLARE DATA_TOO_LONG_ERROR CONDITION FOR 1406;
  DECLARE HAVE_ERROR INTEGER DEFAULT 0;
  DECLARE MYSQL_ERROR_CODE VARCHAR(4) DEFAULT '0000';
  DECLARE SHORT_DESCRIPTION VARCHAR(50) DEFAULT 'NOT FOUND ERROR';
  DECLARE CONTINUE HANDLER FOR DUPLICATE_ENTRY_ERROR
  BEGIN
    SET HAVE_ERROR = 1;
    SET MYSQL_ERROR_CODE = '1062';
    SET SHORT_DESCRIPTION = 'DUPLICATE ENTRY ERROR';
  END;
  DECLARE CONTINUE HANDLER FOR DATA_TOO_LONG_ERROR
  BEGIN
    SET HAVE_ERROR = 1;
    SET MYSQL_ERROR_CODE = '1406';
    SET SHORT_DESCRIPTION = 'DATA TOO LONG ERROR';
  END;
  DROP TEMPORARY TABLE IF EXISTS TEMP_TBL_REPORT;
  CREATE TEMPORARY TABLE TEMP_TBL_REPORT(
    Have_Error INT,
    MySql_Error_Code VARCHAR(4),
    Short_Description VARCHAR(50));
  INSERT INTO TBL_CATEGORIES(CategoryID,CategoryName,Description) VALUES (CATEGORY_ID, CATEGORY_NAME, DESCRIPTION);
  INSERT INTO TEMP_TBL_REPORT(Have_Error, MySql_Error_Code, Short_Description) VALUES (HAVE_ERROR, MYSQL_ERROR_CODE, SHORT_DESCRIPTION);
  SELECT * FROM TEMP_TBL_REPORT;
END$


/***************************************************
End of file
****************************************************/