/***************************************************
Source for Chapter 3 , Example 3.6
How to use WHILE … END WHILE control CURSOR
****************************************************/

DELIMITER $
DROP PROCEDURE IF EXISTS CURSOR_WHILE$
CREATE PROCEDURE CURSOR_WHILE()
BEGIN
  DECLARE CATEGORY_ID INTEGER;
  DECLARE CATEGORY_NAME VARCHAR(15);
  DECLARE DESCRIPTION LONGTEXT;
  DECLARE NUMBER_ROW INT DEFAULT 0;
  DECLARE EOF INT DEFAULT 0;
  DECLARE C_TBL_CATEGORIES CURSOR FOR SELECT * FROM TBL_CATEGORIES;
  DECLARE CONTINUE HANDLER FOR NOT FOUND SET EOF = 1;
  OPEN C_TBL_CATEGORIES;
  CURSOR_FOR_TBL_CATEGORIES : WHILE (NOT EOF) DO
    FETCH C_TBL_CATEGORIES INTO CATEGORY_ID,CATEGORY_NAME,DESCRIPTION;
    IF EOF THEN
      LEAVE CURSOR_FOR_TBL_CATEGORIES;
    END IF;
    SET NUMBER_ROW = NUMBER_ROW + 1;
    SELECT CATEGORY_ID AS 'CATEGORY ID',CATEGORY_NAME AS 'CATEGORY NAME',DESCRIPTION AS 'DESCRIPTION';
  END WHILE CURSOR_FOR_TBL_CATEGORIES;
  CLOSE C_TBL_CATEGORIES;
  SET EOF = 0;
  SELECT NUMBER_ROW AS 'COUNT ROW';
END$


/***************************************************
End of file
****************************************************/