/***************************************************
Source for Chapter 3 , Example 3.4
How to use LOOP control CURSOR
****************************************************/

DELIMITER $
DROP PROCEDURE IF EXISTS CURSOR_LOOP$
CREATE PROCEDURE CURSOR_LOOP()
BEGIN
  DECLARE CATEGORY_ID INTEGER;
  DECLARE CATEGORY_NAME VARCHAR(15);
  DECLARE DESCRIPTION LONGTEXT;
  DECLARE NUMBER_ROW INT DEFAULT 0;
  DECLARE EOF INT DEFAULT 0;
  DECLARE C_TBL_CATEGORIES CURSOR FOR SELECT * FROM TBL_CATEGORIES;
  DECLARE CONTINUE HANDLER FOR NOT FOUND SET EOF = 1;
  OPEN C_TBL_CATEGORIES;
  CURSOR_FOR_TBL_CATEGORIES : LOOP
    FETCH C_TBL_CATEGORIES INTO CATEGORY_ID,CATEGORY_NAME,DESCRIPTION;
    IF EOF THEN
      LEAVE CURSOR_FOR_TBL_CATEGORIES;
    ELSE
      SET NUMBER_ROW = NUMBER_ROW + 1;
      SELECT CATEGORY_ID AS 'CATEGORY ID',CATEGORY_NAME AS 'CATEGORY NAME',DESCRIPTION AS 'DESCRIPTION';
    END IF;
  END LOOP CURSOR_FOR_TBL_CATEGORIES;
  CLOSE C_TBL_CATEGORIES;
  SET EOF = 0;
  SELECT NUMBER_ROW AS 'COUNT ROW';
END$


/***************************************************
End of file
****************************************************/