/***************************************************
Source for Chapter 3 , Example (No run number)
PHP and MySQL
****************************************************/

DELIMITER $
DROP PROCEDURE IF EXISTS GET_DATA_CATEGORIES$
DROP TEMPORARY TABLE IF EXISTS TEMP_TBL_CATEGORIES$
CREATE PROCEDURE GET_DATA_CATEGORIES()
BEGIN
  DECLARE CATEGORY_ID INTEGER;
  DECLARE CATEGORY_NAME VARCHAR(15);
  DECLARE DESCRIPTION LONGTEXT;
  DECLARE EOF INT DEFAULT 0;
  DECLARE C_TBL_CATEGORIES CURSOR FOR SELECT * FROM TBL_CATEGORIES;
  DECLARE CONTINUE HANDLER FOR NOT FOUND SET EOF = 1;
  CREATE TEMPORARY TABLE IF NOT EXISTS TEMP_TBL_CATEGORIES(
    CategoryID INT,
    CategoryName VARCHAR(15),
    Description LONGTEXT);
  OPEN C_TBL_CATEGORIES;
  CURSOR_FOR_TBL_CATEGORIES : LOOP
    FETCH C_TBL_CATEGORIES INTO CATEGORY_ID,CATEGORY_NAME,DESCRIPTION;
    IF EOF THEN
      LEAVE CURSOR_FOR_TBL_CATEGORIES;
    ELSE
      INSERT INTO TEMP_TBL_CATEGORIES(CategoryID,CategoryName,Description) VALUES (CATEGORY_ID,CATEGORY_NAME,DESCRIPTION);
    END IF;
  END LOOP CURSOR_FOR_TBL_CATEGORIES;
  CLOSE C_TBL_CATEGORIES;
  SET EOF = 0;
  SELECT * FROM TEMP_TBL_CATEGORIES;
END$


/***************************************************
End of file
****************************************************/