/***************************************************
Source for Chapter 6 , Example 6.1
How to use NEW and OLD statement
****************************************************/

DELIMITER $
DROP TRIGGER IF EXISTS BEFORE_INSERT_TRIGGER$
CREATE TRIGGER BEFORE_INSERT_TRIGGER BEFORE INSERT
ON TBL_TRANSACTION_ITEMS
FOR EACH ROW
BEGIN
  DECLARE DETAIL LONGTEXT;
  DECLARE LOGDATETIME DATETIME;
  SET DETAIL = CONCAT('Trigger Before Insert Started : TransactionID = ',NEW.TransactionID,' : ItemID = ',NEW.ItemID,' : Activity = ',NEW.Activity,' : Amount = ',NEW.Amount);
  SET LOGDATETIME = NOW();
  INSERT INTO TBL_LOG(Detail,LogDateTime) VALUES(DETAIL,LOGDATETIME);
END$
DROP TRIGGER IF EXISTS AFTER_INSERT_TRIGGER$
CREATE TRIGGER AFTER_INSERT_TRIGGER AFTER INSERT
ON TBL_TRANSACTION_ITEMS
FOR EACH ROW
BEGIN
  DECLARE DETAIL LONGTEXT;
  DECLARE LOGDATETIME DATETIME;
  SET DETAIL = CONCAT('Trigger After Insert Started : TransactionID = ',NEW.TransactionID,' : ItemID = ',NEW.ItemID,' : Activity = ',NEW.Activity,' : Amount = ',NEW.Amount);
  SET LOGDATETIME = NOW();
  INSERT INTO TBL_LOG(Detail,LogDateTime) VALUES(DETAIL,LOGDATETIME);
END$
DROP TRIGGER IF EXISTS BEFORE_UPDATE_TRIGGER$
CREATE TRIGGER BEFORE_UPDATE_TRIGGER BEFORE UPDATE
ON TBL_TRANSACTION_ITEMS
FOR EACH ROW
BEGIN
  DECLARE DETAIL LONGTEXT;
  DECLARE LOGDATETIME DATETIME;
  SET DETAIL = CONCAT('Trigger Before Update Started : TransactionID = ',OLD.TransactionID,' : ItemID = ',OLD.ItemID,' : Activity = ',OLD.Activity,' : Amount = ',OLD.Amount);
  SET LOGDATETIME = NOW();
  INSERT INTO TBL_LOG(Detail,LogDateTime) VALUES(DETAIL,LOGDATETIME);
END$
DROP TRIGGER IF EXISTS AFTER_UPDATE_TRIGGER$
CREATE TRIGGER AFTER_UPDATE_TRIGGER AFTER UPDATE
ON TBL_TRANSACTION_ITEMS
FOR EACH ROW
BEGIN
  DECLARE DETAIL LONGTEXT;
  DECLARE LOGDATETIME DATETIME;
  SET DETAIL = CONCAT('Trigger After Update Started : TransactionID = ',NEW.TransactionID,' : ItemID = ',NEW.ItemID,' : Activity = ',NEW.Activity,' : Amount = ',NEW.Amount);
  SET LOGDATETIME = NOW();
  INSERT INTO TBL_LOG(Detail,LogDateTime) VALUES(DETAIL,LOGDATETIME);
END$
DROP TRIGGER IF EXISTS BEFORE_DELETE_TRIGGER$
CREATE TRIGGER BEFORE_DELETE_TRIGGER BEFORE DELETE
ON TBL_TRANSACTION_ITEMS
FOR EACH ROW
BEGIN
  DECLARE DETAIL LONGTEXT;
  DECLARE LOGDATETIME DATETIME;
  SET DETAIL = CONCAT('Trigger Before Delete Started : TransactionID = ',OLD.TransactionID,' : ItemID = ',OLD.ItemID,' : Activity = ',OLD.Activity,' : Amount = ',OLD.Amount);
  SET LOGDATETIME = NOW();
  INSERT INTO TBL_LOG(Detail,LogDateTime) VALUES(DETAIL,LOGDATETIME);
END$
DROP TRIGGER IF EXISTS AFTER_DELETE_TRIGGER$
CREATE TRIGGER AFTER_DELETE_TRIGGER AFTER DELETE
ON TBL_TRANSACTION_ITEMS
FOR EACH ROW
BEGIN
  DECLARE DETAIL LONGTEXT;
  DECLARE LOGDATETIME DATETIME;
  SET DETAIL = CONCAT('Trigger After Delete Started : TransactionID = ',OLD.TransactionID,' : ItemID = ',OLD.ItemID,' : Activity = ',OLD.Activity,' : Amount = ',OLD.Amount);
  SET LOGDATETIME = NOW();
  INSERT INTO TBL_LOG(Detail,LogDateTime) VALUES(DETAIL,LOGDATETIME);
END$


/***************************************************
End of file
****************************************************/