
<?php echo $this->tag->form("register/create") ?>


<?php echo $this->getContent(); ?>


<div align="center">
    <h1>Register users</h1>
</div>

<table>
<!--
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    --><tr>
        <td align="right">
            <label for="username">Username *:</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("username", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="fname">ชื่อ *:</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("fname", "size" => 30)) ?>
        </td>

        <td align="right">
            <label for="lname">สกุล *:</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("lname", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="email">อีเมล์ :</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("email", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="date">วันเกิด :</label>
        </td>
        <td align="left">
                <?php echo Phalcon\Tag::dateField(array("date", "value" => "0000-00-00")); ?>
        </td>
    </tr>
    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Save") ?> &nbsp;&nbsp; 
        <?php echo $this->tag->linkTo(array("register", "Go Back")) ?>
        </td>
    <tr>
</table>

</form>
