<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>
<div align="center">
    <h1>Users</h1>
</div>

<table class="" width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("users/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("users/new", "Create ")); ?>
        </td>
    <tr>
</table>
<table class="browse" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th>Username</th>
            <th>Fname</th>
            <th>Lname</th>
            <th>Email</th>
            <th>Date</th>
            <th colspan="2">&nbsp;</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $user) { ?>
        <tr>
            <td><?php echo $user->id ?></td>
            <td><?php echo $user->username ?></td>
            <td><?php echo $user->fname ?></td>
            <td><?php echo $user->lname ?></td>
            <td><?php echo $user->email ?></td>
            <td><?php echo $user->date ?></td>
            <td><?php echo $this->tag->linkTo(array("users/edit/" . $user->id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("users/delete/" . $user->id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="8" align="right">
                <table class="inbrowse" align="center" width="50%">
                    <tr>
                        <td><?php echo $this->tag->linkTo("users/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("users/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("users/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("users/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>


