/***************************************************
Source for Chapter 8 , Example 8.3
How to use Aggregate Function
****************************************************/

DELIMITER $
DROP FUNCTION IF EXISTS AGGREGATE_FUNCTION$
CREATE FUNCTION AGGREGATE_FUNCTION(CHOICE INT)
RETURNS FLOAT
BEGIN
  DECLARE RESULT FLOAT;
  CASE
    WHEN (CHOICE = 1) THEN
      SELECT AVG(AMOUNT) INTO RESULT FROM TBL_TRANSACTION_ITEMS WHERE ACTIVITY = 'IN';
    WHEN (CHOICE = 2) THEN
      SELECT COUNT(AMOUNT) INTO RESULT FROM TBL_TRANSACTION_ITEMS WHERE ACTIVITY = 'IN';
    WHEN (CHOICE = 3) THEN
      SELECT MAX(AMOUNT) INTO RESULT FROM TBL_TRANSACTION_ITEMS WHERE ACTIVITY = 'IN';
    WHEN (CHOICE = 4) THEN
      SELECT MIN(AMOUNT) INTO RESULT FROM TBL_TRANSACTION_ITEMS WHERE ACTIVITY = 'IN';
    WHEN (CHOICE = 5) THEN
      SELECT SUM(AMOUNT) INTO RESULT FROM TBL_TRANSACTION_ITEMS WHERE ACTIVITY = 'IN';
  END CASE;
  RETURN RESULT;
END$
DROP PROCEDURE IF EXISTS SHOW_RESULT$
CREATE PROCEDURE SHOW_RESULT()
BEGIN
  SELECT AGGREGATE_FUNCTION(1) AS 'AVG RESULT',
  AGGREGATE_FUNCTION(2) AS 'COUNT RESULT',
  AGGREGATE_FUNCTION(3) AS 'MAX RESULT',
  AGGREGATE_FUNCTION(4) AS 'MIN RESULT',
  AGGREGATE_FUNCTION(5) AS 'SUM RESULT';
END$


/***************************************************
End of file
****************************************************/